### ISSUE TITLE
Broken link in setup.md

### ISSUE THREAD

**Issue by aprovo** [NYULibraries/dlts-enm-tct-backend#1]
This is a small thing, but there is a broken link in this setup.md file when viewed here on Github: https://github.com/NYULibraries/dlts-enm-tct-backend/blob/07455a660fb2cb8bc91a54f7f12d150923678157/documentation/docs/setup.md

In the sentence "If you are not using the existing set of EPUBs, please see the adding a new EPUB section for instructions on how to configure the system to accept a new EPUB" the link is broken.

**Comment by MattBroach** [comment]
The docs here were built with the HTML output in mind, rather than github viewing -- if you look at the built HTML output (currently [here](https://nyuapi.infoloom.nyc/media/docs/backend/setup/)) you'll see that link works.  I'm not sure it's possible to design the links in a way such that they work on both github and the built HTML.

**Comment by aprovo** [comment]
Ok cool! No prob.
